#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Overture-Keywords
version:      1.2
version_from: Keywords.pm
installdirs:  site
requires:
    LWP::UserAgent:                0
    Carp:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
